Vy187/quack

server.js
set up server routes in the server.js
=> edited the server.js

utils/auth.js
added a auth.js file in the folder so we can require login to view certain parts of the application.
=> created a utility folder 

seeds/commentData.js, seeds/userData.js
Added all the seeds files need for now and added users to the userData.js seed file.
=> added seeds files and seed info to users

models/Comment.js, models/Post.js, models/index.js
updated the post and comment models
=> Models folder

views/layouts/main.handlebars
made a nav bar in the main.handlebars
=> created a nav-bar 

seeds/commentData.js, seeds/index.js, seeds/postData.js
Made changes to the post, comment, index seed files
=> added code to the seed files based on the models

views/login.handlebars
created a login handlebars file and have connected it to a login.js which will be in the public folder.
=> created the login.handlebars 

models/Comment.js, models/Post.js, package.json, server.js
=> Package file

server.js
linked the helper file, now the server won't give an error message
=> linked the helper file to the server.js

.env.EXAMPLE, views/homepage.handlebars, views/layouts/main.handlebars
changed some code in the main.handlebars as well that doesn't disable the logout nav bar button.
=> Created code for the homepage handlebars

views/edit-post.handlebars
This code should allow you to select a single post and delete, as it is also connected to the edit.js in the public folder we need to create.
=> created an edit-post file 

views/homepage.handlebars
deleted the # that did not need to be there in line16
=> corrected the error in the homepage handlebars

controllers/api/index.js, controllers/api/userRoutes.js
added api routes and added code for user routes
=> added api folder to controllers and added code to a user and index file

views/profileallposts.handlebars
added this so that when selected you can see posts by the profile tab when logged in
=> added a profile-all-posts.handlebars

views/signup.handlebars
this connects to the login.js which has the functions for sign-up within that file.
=> created a signup.handlebars

views/edit-post.handlebars, views/layouts/profile.handlebars, views/new-post.handlebars
also edited the profile handlebars and the edit-post handlebars for errors.
=> created a new-post.handlebars 

views/single-post.handlebars
This is to add comments to a single post as well as to see if a post has comments with it.
=> created a single-post page 

controllers/api/commentRoutes.js, controllers/api/postRoutes.js
created get, post, put, and delete routes for both comment and post routes
=> added comment and post routes to the api routes

controllers/api/postRoutes.js, controllers/dashboardRoutes.js, controllers/homeRoutes.js, models/Post.js, public/css/style.css, seeds/postData.js, views/dashboard.handlebars, views/edit.handlebars, views/partials/post-body.handlebars
added css changes as well as routes and handlebars
=> got rid of title from routes and handlebars and added css

public/css/style.css, views/layouts/main.handlebars
with the border styles and the login and the hover effect
=> made changes to the css

package.json, server.js
Sorry I have been slacking, this didn't do much but made the package look neater, I'm going to work on the likes and dislikes now
=> Uprdate package

controllers/api/userRoutes.js, public/css/style.css, views/dashboard.handlebars, views/layouts/main.handlebars
This change was to make sure that people have to login to view the users tab in the nav bar.
=> added a change to user routes 

package.json, utils/helpers.js, views/partials/post-body.handlebars
date now reads in a format where it is relative to current time
=> added a new package that reads the create date in different way
